# one line comment

simpe_key                 = "тест_кириллицы";
simple_key_without_spaces = value;

string_key =
	"value"
	'string';

multiline_string = `
	multiline
	string
	123
`;

int_key = -123.456;
bool_key = true;

expression1 argument1 "argument2" 123;

# comment can be everywhere
group_directive_without_arguments {
	expression1 argument2 "string" 123 true;
	expression2 argument3 "string111" 123321 false;
	children_group "some argument" {
		# child group. Can be empty. This is equivalent to directive `children_group "some argument"`
	}
}

group_directive_with_argument "some other argument" 'second argument' {
	child_val = "children value";
}

