some directive;
group1 param1 {
    group2 param2 {
        group3 param3 {
            key       "value";
            int_key   123;
            float_key 123.321;
            bool_key  true;
        }
        external_vars "Concatenate with" EXTERNAL_VAR "and integer" 123;
    }
}